# org.gradle.jvmargs=-Xmx1536M
# android.useAndroidX=true
# android.enableJetifier=true


# Gradle & JVM
org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Java & Kotlin target
kotlin.jvm.target=17
android.defaults.buildfeatures.buildconfig=true

# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true
