// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default: 
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvykMsWLlXCLvwNT4KMgUFo2QNAK24QCw',
    appId: '1:748397217426:web:74c734ec92987c0b4d084b',
    messagingSenderId: '748397217426',
    projectId: 'inventory-management-sys-d77af',
    authDomain: 'inventory-management-sys-d77af.firebaseapp.com',
    storageBucket: 'inventory-management-sys-d77af.firebasestorage.app',
    measurementId: 'G-2Y1X1NPG54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYx0kP4DG9GMnpyp_JNVQLvFZW2UQYs8',
    appId: '1:748397217426:android:14f43e687dc56dc34d084b',
    messagingSenderId: '748397217426',
    projectId: 'inventory-management-sys-d77af',
    storageBucket: 'inventory-management-sys-d77af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZy0lWoysDdBd70Iuy9IeYNLkq5EbY0g',
    appId: '1:748397217426:ios:982627e793b219f24d084b',
    messagingSenderId: '748397217426',
    projectId: 'inventory-management-sys-d77af',
    storageBucket: 'inventory-management-sys-d77af.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZy0lWoysDdBd70Iuy9IeYNLkq5EbY0g',
    appId: '1:748397217426:ios:982627e793b219f24d084b',
    messagingSenderId: '748397217426',
    projectId: 'inventory-management-sys-d77af',
    storageBucket: 'inventory-management-sys-d77af.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvykMsWLlXCLvwNT4KMgUFo2QNAK24QCw',
    appId: '1:748397217426:web:ecba870a11933b5f4d084b',
    messagingSenderId: '748397217426',
    projectId: 'inventory-management-sys-d77af',
    authDomain: 'inventory-management-sys-d77af.firebaseapp.com',
    storageBucket: 'inventory-management-sys-d77af.firebasestorage.app',
    measurementId: 'G-9Y32HKDMC2',
  );
}
