// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTY97o9PLUqEkUK2N4TUaliuCawMvWiE',
    appId: '1:1097245801564:web:c413d9ba1f6cd2981fba99',
    messagingSenderId: '1097245801564',
    projectId: 'inventory-sys-974aa',
    authDomain: 'inventory-sys-974aa.firebaseapp.com',
    storageBucket: 'inventory-sys-974aa.firebasestorage.app',
    measurementId: 'G-FVNGLX5D83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD7CGsX-mDrgMCCi-f4d9ahXIU56ML0MU',
    appId: '1:1097245801564:android:9700787690f4cbd81fba99',
    messagingSenderId: '1097245801564',
    projectId: 'inventory-sys-974aa',
    storageBucket: 'inventory-sys-974aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6C59VqUjPWxlnAm2D-cfjTrdIuCyUGk',
    appId: '1:1097245801564:ios:7c8d5ae311a1cb5d1fba99',
    messagingSenderId: '1097245801564',
    projectId: 'inventory-sys-974aa',
    storageBucket: 'inventory-sys-974aa.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb6C59VqUjPWxlnAm2D-cfjTrdIuCyUGk',
    appId: '1:1097245801564:ios:7c8d5ae311a1cb5d1fba99',
    messagingSenderId: '1097245801564',
    projectId: 'inventory-sys-974aa',
    storageBucket: 'inventory-sys-974aa.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnTY97o9PLUqEkUK2N4TUaliuCawMvWiE',
    appId: '1:1097245801564:web:3d3e20773544f22f1fba99',
    messagingSenderId: '1097245801564',
    projectId: 'inventory-sys-974aa',
    authDomain: 'inventory-sys-974aa.firebaseapp.com',
    storageBucket: 'inventory-sys-974aa.firebasestorage.app',
    measurementId: 'G-4V95JQ2GBH',
  );
}
